
spring:
  application:
    name: user-service
  devtools:
    restart:
     enabled: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
        mode: polling
        period: 10000
server:
  port: 8080
  servlet:
    context-path: /api/user



eureka:
  client:
    enabled: false

feign:
  hystrix:
    enabled: true


management:
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh, info


#spring.zipkin.base-url=http://localhost:9411
#spring.zipkin.sender.type=web
#spring.sleuth.sampler.probability=1
#eureka.client.serviceUrl.defaultZone = http://localhost:8010/eureka


